#!/usr/bin/env python
# -*- coding: utf-8 -*-

print("Content-Type: text/html")
print

print ("""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>UDepLambda Demo</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<p>Sorry, This demo has been discontinued.</p>
<p>See <a href="https://github.com/sivareddyg/UDepLambda/issues/18">issue</a></p>
</body>
</html>
""")
